includes:
  - https://github.ibm.com/cloud-docs/ContinuousDelivery
  - https://github.ibm.com/cloud-docs/devsecops
  - https://github.ibm.com/cloud-docs/containers
  - https://github.ibm.com/cloud-docs/solution-tutorials
  - https://github.ibm.com/cloud-docs/node
  - https://github.ibm.com/cloud-docs/go
  - https://github.ibm.com/cloud-docs/java
  - https://github.ibm.com/cloud-docs/swift
